on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  main:
    if: github.actor != 'crosscurve-bot'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - run: npm install
      - run: npm run compile
      - run: |
          git config --global user.name "crosscurve-bot"
          git config --global user.email "bot@crosscurve.fi"
          git add .
          git commit -m "Apply changes" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"
        if: ${{ success() && github.event_name != 'pull_request' }}
